name: Build Wheels

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_wheels_linux_x64:
    name: Build wheels on ubuntu-24.04 (x64) for PyPi
    uses: ./.github/workflows/_build_wheel_job.yml
    with:
      runner: ubuntu-24.04
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

  build_wheels_linux_arm64:
    name: Build wheels on ubuntu-24.04-arm (arm64) for PyPi
    uses: ./.github/workflows/_build_wheel_job.yml
    with:
      runner: ubuntu-24.04-arm
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
